# Example values for installing a tagged release.

installCRDs: true

image:
  repository: ghcr.io/wyvernzora/cnpg-dbclaim-operator
  tag: v0.2.0
  pullPolicy: IfNotPresent

replicaCount: 1
leaderElection: true

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 64Mi

metrics:
  enabled: true
  port: 8080
  serviceType: ClusterIP
