version: "2"
run:
  go: "1.25"
linters:
  default: none
  enable:
    - errcheck
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unparam
    - unused
  settings:
    gocritic:
      disabled-checks:
        - ifElseChain
        - singleCaseSwitch
    gosec:
      excludes:
        - G115
        - G404
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
          - unparam
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/wyvernzora/cnpg-dbclaim-operator
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
