---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cnpg.wyvernzora.io
  resources:
  - databaseclaims
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - cnpg.wyvernzora.io
  resources:
  - databaseclaims/finalizers
  - roleclaims/finalizers
  verbs:
  - update
- apiGroups:
  - cnpg.wyvernzora.io
  resources:
  - databaseclaims/status
  - roleclaims/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cnpg.wyvernzora.io
  resources:
  - roleclaims
  verbs:
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - postgresql.cnpg.io
  resources:
  - clusters
  verbs:
  - get
  - list
  - watch
